services:
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus/config/:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
    environment:
      TZ: "Europe/Moscow"

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

  grafana:
    image: grafana/grafana:10.4.12
    container_name: grafana
    user: root
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always
    environment:
      TZ: "Europe/Moscow"

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    hostname: logstash
    labels:
      co.elastic.logs/module: logstash
    volumes:
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=LOGSTASH
      - ELASTIC_PASSWORD=ELASTIC_PASSWORD
      - ELASTIC_HOSTS=http://elasticsearch:9200

  kibana:
    depends_on:
      - logstash
    container_name: kibana
    image: kibana:8.15.3
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - ./kibana/data:/usr/share/kibana/data
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_USERNAME=KIBANA
      - ELASTICSEARCH_PASSWORD=KIBANA_PASSWORD
